/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#000000",
        "surface-container": "#191919",
        "surface-variant": "#262626",
        "primary-fixed": "#fed023",
        "on-surface": "#ffffff",
        "on-tertiary-container": "#015a00",
        "secondary": "#ff6d8d",
        "outline-variant": "#484848",
        "outline": "#757575",
        "primary-container": "#ebbf01",
        "on-primary-fixed-variant": "#655000",
        "tertiary-fixed": "#00fd00",
        "secondary-fixed-dim": "#ffaeba",
        "surface-bright": "#2c2c2c",
        "inverse-on-surface": "#555555",
        "on-secondary-fixed-variant": "#a30040",
        "on-error": "#450900",
        "surface-container-high": "#1f1f1f",
        "on-background": "#ffffff",
        "on-secondary": "#480018",
        "on-primary-fixed": "#433500",
        "surface-tint": "#fed023",
        "on-tertiary-fixed": "#014500",
        "surface": "#0e0e0e",
        "surface-container-low": "#131313",
        "error": "#ff7351",
        "surface-dim": "#0e0e0e",
        "primary": "#fed023",
        "inverse-surface": "#f9f9f9",
        "error-dim": "#d53d18",
        "on-tertiary-fixed-variant": "#026500",
        "on-primary": "#594700",
        "error-container": "#b92902",
        "inverse-primary": "#735c00",
        "on-tertiary": "#026400",
        "tertiary-container": "#00fd00",
        "primary-dim": "#eec209",
        "on-secondary-container": "#fff6f5",
        "tertiary-dim": "#01ed00",
        "secondary-container": "#bc004b",
        "on-surface-variant": "#ababab",
        "tertiary": "#9fff88",
        "surface-container-highest": "#262626",
        "primary-fixed-dim": "#eec209",
        "on-secondary-fixed": "#6e0028",
        "on-error-container": "#ffd2c8",
        "tertiary-fixed-dim": "#01ed00",
        "background": "#0e0e0e",
        "on-primary-container": "#4d3d00",
        "secondary-fixed": "#ffc2ca",
        "secondary-dim": "#e2165f"
      },
      fontFamily: {
        "headline": ["Epilogue", "sans-serif"],
        "body": ["Space Grotesk", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      animation: {
        "scroll": "scroll 20s linear infinite",
        "spin-slow": "spin 8s linear infinite",
      },
      keyframes: {
        scroll: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
    },
  },
  plugins: [],
}
